version: 2
#dependencies:
#  pre:
#    - gem install bundler --pre
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      # - run:
      #     command: gem install bundler --pre
      - run:
          name: Print the Current Time
          command: date
      - run: bundle install --path vendor/bundle
      - run:
          name: Run danger
          command: bundle exec danger
